spring: 
  profiles:
    active:
    - dev
--- 
server:
  port: 9001

mybatis:
  config-location:classpath:  mybatis/mybatis.cfg.xml
  type-aliases-package: com.zj.springcloud.enties
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: dev
  application:
          name: microservicecloud-dept
  datasource:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/clouddb01
          username: root
          password: 110120...
          dbcp2:
            min-idle: 5
            initial-size: 5
            max-total:  5
            max-wait-millis:  200

eureka:
  client:
    service-url:
#      defaultZone:  http://localhost:9011/eureka   #单机版
      defaultZone:  http://eureka9011.com:9011/eureka   #单机版
#      defaultZone:  http://eureka9011.com:9011/eureka/,http://eureka9012.com:9012/eureka/,http://eureka9013.com:9013/eureka/

  instance:
    instance-id: springcloud-9001
#    instance-id: microservicecloud_dept8001-hystrix
    prefer-ip-address: true     #显示访问路径ip
info:
  app.name: zj-microservercloud
  company.name: www.zj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
server:
  port: 9001

mybatis:
  config-location:classpath:  mybatis/mybatis.cfg.xml
  type-aliases-package: com.zj.springcloud.enties
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  profiles: test
  application:
          name: microservicecloud-dept
  datasource:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/clouddb02
          username: root
          password: 110120...
          dbcp2:
            min-idle: 5
            initial-size: 5
            max-total:  5
            max-wait-millis:  200

eureka:
  client:
    service-url:
#      defaultZone:  http://localhost:9011/eureka   #单机版
      defaultZone:  http://eureka9011.com:9011/eureka   #单机版
#      defaultZone:  http://eureka9011.com:9011/eureka/,http://eureka9012.com:9012/eureka/,http://eureka9013.com:9013/eureka/

  instance:
    instance-id: springcloud-9001
#    instance-id: microservicecloud_dept8001-hystrix
    prefer-ip-address: true     #显示访问路径ip
info:
  app.name: zj-microservercloud
  company.name: www.zj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

